import sys
import time

def typewriter_effect(text, delay = 0.18):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(delay)
    sys.stdout.write("\n")


def main():
    typewriter_effect("But this is too much... I don't want this", delay=0.18)
    typewriter_effect("WHAT DO YOU WANT?", delay=0.18)
    typewriter_effect("........")
    typewriter_effect("YOU WANNA GO BACK TO YOUR SHITJOB......", delay=0.18)
    typewriter_effect("FUCKING CONDO AND WATCHING SITCOMS??????", delay=0.18)
    typewriter_effect("FUCK YOU.....I WON'T DO IT", delay=0.18)
    typewriter_effect("..................", delay=0.18)
    typewriter_effect(".................", delay=0.18)
    typewriter_effect("He's me.......", delay=0.18)
    typewriter_effect(".........", delay=0.18)
    typewriter_effect("I can see through your eyes....its corrosive", delay=0.18)
    typewriter_effect("Talking about.....the yellow king", delay=0.18)
    typewriter_effect("..........", delay=0.18)
    typewriter_effect("Someone will more likely remember that you ever hurt them....rather than help them", delay=0.18)
    typewriter_effect("IM TONY MONTANA.....YOU FUCKED WITH ME YOU'RE FUCKING WITH THE BEST", delay=0.18)
    typewriter_effect("The world chico.....and everything in it", delay=0.18)
    typewriter_effect("SAY HELLO TO MY LITTLE FRIEND", delay=0.18)
    typewriter_effect("You say you were locked and loaded?", delay=0.18)
    typewriter_effect("He once killed a man with a...", delay=0.18)
    typewriter_effect("Pencil...I knew it", delay=0.18)
    typewriter_effect("WITH A FUCKING PENCIL.....", delay=0.18)
    typewriter_effect("He's a man of focus....commitment.....and sheer fucking will", delay=0.18)
    typewriter_effect(".......", delay=0.18)
    typewriter_effect("Noise complain?", delay=0.18)
    typewriter_effect("Yeah....noise complain", delay=0.18)
    typewriter_effect(".....", delay=0.18)
    typewriter_effect("You dont fight....you will die", delay=0.18)
    typewriter_effect("It Felt good.....", delay=0.18)
    typewriter_effect("We're the ones who lives.....", delay=0.18)
    typewriter_effect("I DIDNT KILL HIM", delay=0.18)
    typewriter_effect("I told you already....Im gonna kill you", delay=0.18)
    typewriter_effect("Are you cooperating?", delay=0.18)
    typewriter_effect("...Look at my eyes sir...you tell me", delay=0.18)
    typewriter_effect("RAISE YOUR GUN", delay=0.18)
    typewriter_effect("We're the ones who lives", delay=0.18)
    typewriter_effect("Talking about....the yellow king", delay=0.18)
    typewriter_effect("......Carcosa.....The Yellow King", delay=0.18)
    typewriter_effect("WHAT ARE YOU GONNA DO? YOU'RE GONNA SHOOT ME HUH?", delay=0.18)
    typewriter_effect(".........", delay=0.18)
    typewriter_effect("SHOOT ME.....FUCKING SHOOT ME.....", delay=0.18)
    typewriter_effect(".......", delay=0.18)
    typewriter_effect("OKAY...YOU LIKE THAT? HUH....YOU WANT MORE?", delay=0.18)
    typewriter_effect("What will you have after 500 years?", delay=0.18)
    typewriter_effect(".....", delay=0.18)
    typewriter_effect("I SAW YOU WITH THE BOX WHAT WAS IN THE BOX?....", delay=0.18)
    typewriter_effect("NAH...WHATS IN THE BOX? WHATS IN THE FUCKING BOX?", delay=0.18)
    typewriter_effect("I took a souvenir....her pretty head", delay=0.18)
    typewriter_effect("Here it comes...", delay=0.18)
    typewriter_effect("I dont carry a gun....I drive", delay=0.18)


if __name__ == "__main__":
    main()